from selenium import webdriver
import getpass,time
user=input('Enter your account name : ')
password=getpass.getpass('Enter your password : ')
driver=webdriver.Chrome('chromedriver_linux64/chromedriver')
driver.get('https://www.instagram.com/accounts/login/?hl=en')
driver.maximize_window()
time.sleep(2)
driver.find_element_by_xpath('//*[@id="react-root"]/section/main/div/article/div/div[1]/div/form/div[2]/div/label/input').send_keys(user)
login=driver.find_element_by_xpath('//*[@id="react-root"]/section/main/div/article/div/div[1]/div/form/div[3]/div/label/input')
login.send_keys(password)
login.submit()
time.sleep(4)
driver.find_element_by_xpath('/html/body/div[4]/div/div/div[3]/button[2]').click()
time.sleep(4)
search=driver.find_element_by_xpath('//*[@id="react-root"]/section/nav/div[2]/div/div/div[2]/input')
search.send_keys('__revu__')
time.sleep(3)
driver.find_element_by_xpath('//*[@id="react-root"]/section/nav/div[2]/div/div/div[2]/div[2]/div[2]/div/a[3]').click()
time.sleep(4)
driver.quit()
print('Process Successfully Completed !!! ')